### ISSUE TITLE
Kali frontend freezing.

### ISSUE THREAD

**Issue by DanielBritze** [aau-network-security/haaukins#191]
We've experince the kali frontend freezing a couple of times now. It stops allowing input.
A frontend restart works in fixing it, but it would still be nice to have fixed at one point.
During the AARS events we had 2 instances on the following teams:
```
Event: | Date | Approx time | Team ID | Type | fix kode | virkede det? | System og browser
Aars HHX | 21/11/2018 | 10:05 | 3a1a65f2 | Frontend crashede | ntp  frontend reset aarshhx -t 3a1a65f2 | Ja | lenovo wimdows - chrome
Aars HTX | 21/11/2018 |   | dav | Frosset | ntp frontend reset aarshtx -t 850cd2ae | Ja | MSi - windows - chrome
```

**Comment by mrturkmen06** [comment]
I think, this could be related with the issue (having 1GB of RAM) #208, I do not have idea in what situation it is happened, but I guess, it is happening when client (user) try to run multiple application on Kali, since it had 1 GB of RAM, it does not handle inputs from user. After merging ram-issue branch into master, we do not have 1 GB of RAM issue after all, then mentioned scenario can be re-simulated.

**Comment by kdhageman** [comment]
@mrturkmen06 We have found this issue difficult to reproduce previously

**Comment by mrturkmen06** [comment]
@kdhageman, then might be good point to close it after we released new version of Haaukins which create VMs  with proper memory size. However, we might need to remove all existing running VMs on the server. (in order to do not face any memory overflow ). In current situation, 20 number of VMs ~ 20 GB of ram consume (just VMs) , but if we release new version and update existing one on the server then 20 VMs will consume 80 GB memory, so we should make some cleaning before updating new release (without 1GB memory issue).

**Comment by kdhageman** [comment]
Although this *could* be related to the other issue (#208), I would not want to assume that it does, and therefore simply close this issue without investigating whether it actually does. So let's leave it open for now.

**Comment by mrturkmen06** [comment]
Overdue, not happened for a long period of time, even server memory goes down to 1.5 GB out of 500 GB. Could be opened if we have experience similar issues.
