### ISSUE TITLE
Launching up Kubernetes on private docker registery

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#222]
Kubernetes will gain a lot of advantages relating to docker containers, management and orchestration of containers will be much easy with implementation of Kubernetes. Since it is open source, deploying it on our private registry will bring a lot of functionalities and great management options. I think, it is a great tool to implement in our infrastructure. Since if there is something wrong on any container which are running, Kubernetes can deal with them by launching backup containers. 

More details about it can be gained from following link : 

https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by tpanum** [comment]
I was introduced to Kubernetes around 2015 by [Kelsey Hightower's Strange Loop talk](https://www.youtube.com/watch?v=pozC9rBvAIs), so I am unsure if the project has severe changed since then.

However, from my perception, Kubernetes is a massive system that tries to do two things:
  1. Creating high-availability (by replication) services that scale dynamically
  2. Provide an abstraction layer over a set of servers, so developers shouldn't care about infrastructure

Based on this, I don't think off-the-self Kubernetes provides any value to haaukins.

**Comment by mrturkmen06** [comment]
I thought that it might be good management environment for containers that we have on Haaukins side, in some point some containers fail to create, at that point with capability of Kubernetes, we can instantly run new ones (as you describes scale dynamically), additionally, information about docker containers'  logs  could be observed easily. Yeah, Kubernetes is a massive system so it covers a lot of other features as well, hence it might not be proper approach to observe docker containers status. Do you have any suggestion regarding to monitoring on docker containers ?

**Comment by tpanum** [comment]
Taking some ideas from Kubernetes could be good idea, e.g. introducing a health check mechanism. Improving stability of VMs/Containers often boil down to errors in the exercises themselves, and in that sense, I think more observability would be helpful.

Additional measures, such as a watch dog mechanism, could be useful and could compensate for some level of poor exercise design.

**Comment by tpanum** [comment]
Before there is a very concrete idea about how this would beneficial, I don't think it is relevant.
