### ISSUE TITLE
Create a time-to-live for events

### ISSUE THREAD

**Issue by tpanum** [aau-network-security/haaukins#235]

**Comment by tpanum** [comment]
The platform generally suffers from a lot of dangling events (events that are forgotten to be stopped). We should implement a feature that requires users to specify a maximum time-to-live for an event of a certain max (i.e. 30 days). This ensures that events will be stopped automatically.

**Comment by JensMyrup** [comment]
I think this is a good idea. We should remember that we might want to use the labs for longer courses, so probably the max setting should be quite long - but default could be 30 days.

**Comment by mrturkmen06** [comment]
Auto killer for events has been created in a docker environment. Rather than putting that functionality into Haaukins itself, a docker container created which takes care of events everyday midnight by checking expected finish time of the events. The auto killer is ready to use, however pending for the issue which is exist in haaukins-webclient repo. [https://github.com/aau-network-security/haaukins-webclient/issues/13]

**Comment by mrturkmen06** [comment]
autokiller deployed.
