### ISSUE TITLE
restart policy for a team 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins#311]
**Is your feature request related to a problem? Please describe.**

Time to time, we are seeing that some teams are not able to connect Kali, it might be caused due to internet connection, connecting it through different tabs or another unexpected error . In this cases, we are logging that team is connected and disconnected information as shown below.

![Screenshot 2019-10-30 at 11 05 38](https://user-images.githubusercontent.com/13614433/67849032-13148c00-fb06-11e9-86fb-2645a0be659b.png)

So, I am thinking to implement a restart policy for teams' front end (kali) when we have lets say more than 10 disconnected message from daemon. 

What do you think about it ? 

**Describe the solution you'd like**

Restart teams' frontend automatically when we have more than 10 disconnected message.

**Comment by kidmose** [comment]
If this is serious problem that needs to be addresses shortterm, then a patch/hack like you suggest might be a good idea.
In principle, I'd like to identify the root cause of a problem like this, in order to fix that, rather than watchdog-like restarts.

**Comment by mrturkmen06** [comment]
As I tried to explain in description, there is no exact reason of having that kind of issue, it could be caused by 
- Poor internet connection 
- Having multiple tabs which are connected to kali 
- or any other user side problem, so it is not crystal clear.

**Comment by kidmose** [comment]
I'm not convimced that it is impossible to identify some different root causes for these errors.
Repeating my self: I see how it can be relevant as a quickfix for now..

**Poor Internet connection:**
 I guess we could distinguish this case by high network latency, dropped packages, something that times out, etc.. In that case I think we can find out where in the platform code base the timeout occurs and maybe solve it with more robust communication, adding retransmission, and the like.

**Multiple tabs:**
So I guess multiple tabs is not supported?
Maybe due to the way we handle sessions, both in the browser and on the server/kali?
And the experiences that user has is that the guac tab with kali is frozen, or broken somehow?

Then we could either 

 1. implement support for multiple tabs with multiple sessions on the kali box (long term), 
 2. we could fix it such that opening a new tab will "lock out" the old tab/session and transparently continue in the new tab/session, with the same session on the kali vm.
 3. or we could give the user an error that says something like "opening multiple tabs for the kali box is not supported".

**Comment by mrturkmen06** [comment]
I did not meant, it is `impossible` to identify :) ( sorry for misunderstanding )

**Comment by mrturkmen06** [comment]
This issue was just a question, no development needed at this stage.

**Comment by jbjjbjjbj** [comment]
The restarting of the lab could also be done by the user via the ctfd interface. 
Like a button where they can reset the kali if it's stuck or they can't connect.

**Comment by kidmose** [comment]
It might be relevant for users to restart target machines too, if they for instance can be BSODed by accident during attack.

**Comment by jbjjbjjbj** [comment]
Yeah exactly. 

Should there then be multiple buttons for resetting individual targets and frontend. Or should there just be a master reset for the whole lab?
