### ISSUE TITLE
documentation: hknd files location?

### ISSUE THREAD

**Issue by scalefree** [aau-network-security/haaukins#340]
I have installed the client & run the tests & the only FAIL I get has to do with config files that accompany **hknd**.  I have no idea where these files are or where to get them.  Better documentation for installation of hknd is definitely in order.

**Comment by mrturkmen06** [comment]
All files regarding to **client** and **hknd** is located in [releases page](https://github.com/aau-network-security/haaukins/releases),

**In order to run it in development mode**:  
 
Source code will be used for this purpose and  following files are required (as described [here](https://github.com/aau-network-security/haaukins/wiki/Configuring-the-daemon)): 
```
- config.yml 
- exercises.yml
- frontends.yml
```
Example content of those files could be found in given link above. 

After placing them on your server (-issue different wildcard domain  if it is not under development mode  -),  or your computer (in development mode), following command can be used;  (- assuming that all configuration files are set and haaukins project cloned- )

(under **haaukins** directory)

` go run app/daemon/main.go --config=/home/user/Desktop/config.yml `

Note: All places of other configuration files could be  written under config.yml file, which can be observed [here](https://github.com/aau-network-security/haaukins/blob/e1ee0be8fa7ff24555e0270c7c747ae5b966bdbf/daemon/daemon.go#L72)

If all required libraries are installed, haaukins will be up, afterwards, any event could be created deleted and modified by specifying development configuration as shown below. 

`HKN_HOST=localhost HKN_SSL_OFF=true hkn event create example --name "Test event" -a 5 -c 25 -e csrf -f kali`

It will spin up all required docker and virtual machines for you. If these explanations are not enough, I am always open to assistance.

 Installation wiki page will be updated with more content, thank you for your feedback :)

**Comment by mrturkmen06** [comment]
I hope, explanations are good enough to make it happen. Since, this question (request) is replied more than 24 Hours ago, I am closing it now, could be re-opened, if necessary.

**Comment by kidmose** [comment]
@scalefree Thanks for cheking out haaukins and for the feedback!
Did you solve the issue?

I'm also interested in hearing a bit more about you experience and understanding how our current documentation on the matter did not work for you.

Did you use the Installation section of the README and the links to the wiki ? (https://github.com/aau-network-security/haaukins#installation)

Any ideas as to what is missing, taking the details above into consideration?

**Comment by mrturkmen06** [comment]
Since there is no further conversation from @scalefree, I am closing this issue. If there is more question to ask, a new issue could be created.
