### ISSUE TITLE
User registration silently truncates passwords

### ISSUE THREAD

**Issue by RasmusRendal** [aau-network-security/haaukins#645]
**Describe the bug**
In the team registration form, passwords have a max length of 20.

[signup.tmpl.html](https://github.com/aau-network-security/haaukins/blob/master/svcs/amigo/resources/private/signup.tmpl.html):
```
<div class="input-div-input">
  <h5>Password</h5>
  <input class="input" name="password" type="password" maxlength="20" minlength="6">
</div>
```
If you paste a newly generated password from a password manager, and this password is longer than 20 characters, only the first 20 characters will be submitted, and without warning you will have a different password than the one in your password manager.

**To Reproduce**
1. Having a string longer than 20 characters in your clipboard
2. Go to the signup team
3. Paste your string into the password field, and register
4. Try and login with the password in your clipboard

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser Firefox
 - Version 88

**Smartphone (please complete the following information):**
 - Device: Pinephone
 - OS: Alpine
 - Browser: Firefox
 - Version: 78

**Comment by mrtrkmn** [comment]
Hi @RasmusRendal 

Thanks a lot for reporting the bug. If you would like to fix / contribute on it, you are welcome to do. If not, I will deal with it, no worries. :)

**Comment by mrtrkmn** [comment]
The password check will happen from backend instead of HTML max/min length restrictions, I have removed the max/min length on HTML level and now once more than 20 or less than 6 characters of passwords are given. User will receive error when they send a signup post request. 

https://github.com/aau-network-security/haaukins/commit/f15ee424522d07ee445560fd2f1a55716bf53eca
